package Commands;

public enum Command {

    //COMMON
    EXIT,
    GET_ALL_PURPOSES,
    GET_ALL_RECORDS,
    GET_ALL_RECORDS_ACCEPTED,

    GET_ALL_RECORDS_NOT_ACCEPTED,

    //ADMIN
    CREATE_PURPOSE,
    EDIT_PURPOSE,
    DELETE_PURPOSE,
    BAN_CLIENT,
    UNBAN_CLIENT,
    UNBAN_MASTER,
    BAN_MASTER,
    REGISTER_MASTER,
    REGISTER_USER,

    GET_ALL_CLIENTS,

    GET_ALL_MASTERS,

    //MASTER
    GET_ALL_CURRENT_MASTER_RECORDS,
    ACCEPT_RECORD_TO_CURRENT_MASTER,

    DELETE_RECORD,

    DELETE_ACCEPTION,

    //CLIENT
    CREATE_RECORD,

    GET_ALL_CURRENT_CLIENT_RECORDS,
    GET_CURRENT_PROFILE,
    EDIT_CURRENT_PROFILE,

}
